# Generated by Django 4.1.7 on 2023-05-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tag_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blog',
            new_name='post',
        ),
    ]
